language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27

script: ./gradlew assembleRelease

notifications:
  email: false
  slack:
    rooms:
      secure: ZqnW6EpCbF4V4rooiSGtpeuMfxraooS8hx5cPEHp8U9m0cF5sl08RDvSyVn7OUdbcZRZkAC7sbqAVKx3D+XjvDgJ85IdhB7zHzPqMUKnniSiZT0V69ELyAuA3H1SyQpOxdyyRCdxTPgqX+pk1GG+35Wtfluc1pKnh8gifjucS87bm8tAi3WZVHDHwTWyPzKy7m4chqX36WrRiFu3QuoG7AAAKzbH6MuxkqmCYbKo7xn4mnaKzJmefTONdP8xrWWV7VYdTazLVzkkAHzs3qLDL4Gw6rU0Kx/O1yDIK42UcBdYE+BRBzFc7OselJw9c4JxnRwzGsHJsFp2xtxq9mDfSJ4uvvBqYhZR9YAFAUZxucMj7DIR1SqkowZxORLwqn/gIlEctV2a4vvKroe+1joW9XoPyIgmjQxU4jnFUIv3nVuBPVHs1GoLvAaGZhJMdGlWUUft7CdPY+68h7vLCe+5GXDkUuTv1tjFOu1EJggHbPu8YwYeLiSaEIHMROUZ4tYNyGukSeTvqhPJ9NhGhjy4NA33QMBFBqEYi2B2DzB2hW5oj4kaWREPkkwoYFSQKeD86kEs18uiWkTD03BKiprH+9EzDFea5DbtB0sg4clz1W5YREwCmNWbV0W1hGEWbPRJmoFakSD+OBnD/er63zRPzoianVW5uIiWxclbFfPIq2k=
    on_success: change
