language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27

script: ./gradlew assembleRelease

notifications:
  email: false
  slack:
    rooms:
      secure: XTH/ENaq49iFCpk1i9H5ZCSEOvFPVokA1CLr/oxySH2wy6j1JW0dfWfT1iXstS8wmySqvMiqbz21TkPugG/LQMh5zbv2q55vDYoGalUs4TQ86Hsg4ytHHogiNGoJdiwFy3LvxJ9joXhIAMDJUz6+hYiqY4WG8VzhoUC8Q/3t32OC+9/inQPX7VhozoQybD2xRyhi87xjpoOjfAMb3NJZBk78bcHvmfsJ9SdIcf2X1Ab03XF/aeReHEg6EELuA+MBbQD+ieXu3m6XL8CRFIVz0FLZV5K1e4XJS7MkrFFmh6KU3LeoYVfldWqaQeB56HEzIhrulrFW0C7x+MKynjziB487+idrUkSMMBjOVwSVOZlLElpRwgyYjYfIfFEUXfsCdNINhLK6ABvbfqS0J8uun2PEABb4+GGejTgo6egZcHbsoM+PryjQShHjhiiX++QBci84XNZFsfDnqWVqby/HBlmkA48yYwzObNqDI6fcNkq3RDnPJTtkKOJIL63PS23s3CxZnLx2cJafIqdEmSBvco7gBMGWd/f1fIa03Dj7JKpUA1dW5DU72I++nDb7q7rSKv6FdPboWE2DbU3nnHfdp/5kOYC6+/an6n9itKrBKagA4MbaN3d7mwCXsoOBMHu8KgABNNVxxIWqLDWzBMsOySHsYW16vHX4SAjTzyyxgh4=
    on_success: change
