language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25

script: ./gradlew assembleRelease

notifications:
  email: false
  slack:
    rooms:
      secure: gGMV3uwVv1/ytPCGOe+Iq41saOYgvNQoYrXkfiPHK36L1POqZN8kwqeb1Au3txH/HsNNvd8+1ozjOyUJahJbwYww4CcIaS2J9G9vW5yCuNvevf5BDU75fW+4jshNl8Bv2P/6cc5oHgjVej172l82rbyo/04md49zmP61WNjxxH9ldTaPoo2gsv2RJwieUY2agXKRcprUHb8BH7B0lCtuANVv1gK45a1nvMTtXTuDE1M9HTYzgi0SPRY+ZQTfkz/oWBajNTVz6tfwWUfSmoD2ahFKd37LOfdwwAvWNJrYONObZH+vqec/SEsPivMhgO4DT7++cSEKksnsmN49cyZl0LVkjt4PkDJP5L/2o9xAm4QDzgNZXHRNiIj5WXZFJIn8b7N7Yi1kxi1OusHrzQTNbEAEYI6Ks2PQcGz2EX0W5XJX1Uqxde5ZTQoAG8jDXoHGjoCiDfpVIvihoTe45LEzs1xa98VjLg8VfS1cjZB7OPbbtWCDUGVI4/eoHJLWjBBI/4j4gwY6YCm9CkC7NEEGvakInogsBy4J4L2co7mg7eZPe8hWh4X6gl5PC7/679C5yBw9VCs+Ruz5cfQRF0o+McbLTdG6/U+AuDd7BPeV88+1d6NU0SMXaWUycJpynSJCQx64esjZSf9IpaO8spCD4ks7BaZ4eqgx/VpuIiYd82Q=
    on_success: change
